version: "3.8"
services:
  fastapi-app:
    build: .
    ports: ["8000:8000"]
    networks: [monitoring]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.47
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    ports: ["9090:9090"]
    networks: [monitoring]

  grafana:
    image: grafana/grafana:10.1
    ports: ["3000:3000"]
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks: [monitoring]

networks:
  monitoring:
    driver: bridge
